name: autofix.ci  # needed to securely identify the workflow
on: [pull_request]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # TODO: add all code-fixing here.

      - uses: autofix-ci/action@hash
