name: autofix.ci

on: [ push, pull_request ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install pre-commit
      - run: pre-commit run --all-files

      - uses: autofix-ci/action@hash
