name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: install-pinned/black@16d510ea9a004e050507ffc22cb0ab52547abc38
      - run: black .

      - uses: install-pinned/reorder_python_imports@0505c9cc1805564ca09905637e20d334990501a0
      - run: |
          shopt -s globstar
          reorder-python-imports --exit-zero-even-if-changed --py310-plus **/*.py

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
