name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Fix lint errors with https://github.com/charliermarsh/ruff
      - uses: install-pinned/ruff@98dba3fbf73694fa9c46c54e46899abdab4553bf
      - run: ruff --fix-only .

      # Format code with https://github.com/psf/black
      - uses: install-pinned/black@ce5c405c664ccae5c4b981b0edc733be8bcc7631
      - run: black .

      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
