name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Fix lint errors with https://github.com/charliermarsh/ruff
      - uses: install-pinned/ruff@61847c0ad4192dc314cc572ac738eda3e16e4617  # 0.0.189
      - run: ruff --fix .

      # Format code with https://github.com/psf/black
      - uses: install-pinned/black@96bfbe5fb50711478a9d6b099c7cdc58d8087858
      - run: black .

      - uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
